### ISSUE TITLE
Doesn't work in Drupal8

### ISSUE THREAD

**Issue by monishdeb** [aydun/uk.squiffle.kam#10]
First of all, this is a great extension to provide accessible and responsive menu in CiviCRM. Code pov loved the implementation :) So I tested it on all 4 CMSs but unfortunately it doesn't work on Drupal8. Here's the screenshot : 
![screen shot 2018-04-11 at 10 06 19 pm](https://user-images.githubusercontent.com/3735621/38676949-4d0434b4-3e7a-11e8-9ac0-b53c482dcf20.png)

Currently SmartMenu css is not applied on civi pages and it failed to override the modified navigation tpl

**Comment by colemanw** [comment]
I've been trying to debug this today and so far have discovered that `hook_civicrm_coreResourceList()` is getting called much later than on the other CMSs.

On D7/WP/J!/BD it works to add footer scripts and set flags like `CIVICRM_DISABLE_DEFAULT_MENU` from within that hook because the rest of the page hasn't been rendered yet, but apparently on D8 the page renders first and *then* core resources are added.

It would be nice to fix that in D8 generally so this doesn't keep causing strange bugs on just one cms.

**Comment by monishdeb** [comment]
I am closing this issue as PR https://github.com/civicrm/civicrm-drupal-8/pull/17 has fixed it. Thanks @colemanw for fixing this issue :)
